db.url=jdbc:postgresql://localhost:5432/day08
db.user=postgres
db.password=admin
db.driver.name=org.postgresql.Driver

#db.url=jdbc:h2:~/test
#db.user=sa
#db.password=
#db.driver.name=org.h2.Driver

#IDE compilation
#db.init.schema.path=day09/ex00/Chat/SocketServer/src/main/resources/schema.sql
#db.init.data.path=day09/ex00/Chat/SocketServer/src/main/resources/data.sql

##Windows compilation
#db.init.schema.path=G:\workdir\myGit\Java_BootCamp\day09\ex00\Chat\src\main\resources\schema.sql
#db.init.data.path=G:\workdir\myGit\Java_BootCamp\day09\ex00\Chat\src\main\resources\data.sql

#console compilation
db.init.schema.path=src/main/resources/schema.sql
db.init.data.path=src/main/resources/data.sql
