#db.url=jdbc:postgresql://localhost:5432/day08
#db.user=postgres
#db.password=admin
#db.driver.name=org.postgresql.Driver

db.url=jdbc:h2:~/test
db.user=sa
db.password=
db.driver.name=org.h2.Driver

db.init.schema.path=day08/ex02/Service/src/main/resources/schema.sql
db.init.data.path=day08/ex02/Service/src/main/resources/data.sql

#db.init.schema.path=src/main/resources/schema.sql
#db.init.data.path=src/main/resources/data.sql
