drop schema if exists tests cascade;

create schema if not exists tests;

create table if not exists tests.products (
    id      integer generated by default as identity (start with 1) primary key,
    name    varchar(50) unique not null,
    price   numeric(10 ,2) not null
);