db.url=jdbc:postgresql://localhost:5432/database
db.user=postgres
db.password=admin
db.driver.name=org.postgresql.Driver
db.path.schema=TanksServer/src/main/resources/schema.sql
db.path.data=TanksServer/src/main/resources/data.sql